import { inShoes } from "../apiServices/Shoes/Models";

export const shoesMocked: inShoes[] = [
  {
    id: crypto.randomUUID(),
    name: "Matsuri Concept",
    image_url: "https://i.ibb.co/nMCwFmhN/matsuri.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Subway - Avenida center",
    fare: 6.5,
    image_url: "https://i.ibb.co/LzXnQyMy/subway.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Burger King - Colombo",
    fare: 7,
    image_url: "https://i.ibb.co/tTpHjhWG/bk.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Burger King - Colombo",
    fare: 7,
    image_url: "https://i.ibb.co/tTpHjhWG/bk.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "McDonald’s - Novo Centro",
    fare: 6,
    image_url: "https://i.ibb.co/PvJt2TRm/mc.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Subway - Avenida center",
    fare: 6,
    image_url: "https://i.ibb.co/LzXnQyMy/subway.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "McDonald’s - Novo Centro",
    fare: 8,
    image_url: "https://i.ibb.co/PvJt2TRm/mc.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Matsuri Concept",
    fare: 6,
    image_url: "https://i.ibb.co/nMCwFmhN/matsuri.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
  {
    id: crypto.randomUUID(),
    name: "Burger King - Colombo",
    fare: 6,
    image_url: "https://i.ibb.co/tTpHjhWG/bk.webp",
    ranting: 4.7,
    opened_at: "08h00",
    closed_at: "17h00",
  },
];
